###########################################################################
#
# Makefile for degminsec2deg program
#
# Mike Dixon, RAP, NCAR, Boulder, CO, 80307, USA
#
# July 2001
#
###########################################################################

include $(RAP_MAKE_INC_DIR)/rap_make_macros

MODULE_TYPE = program
TARGET_FILE = degminsec2deg

LOC_INCLUDES =
LOC_CFLAGS =
LOC_LDFLAGS = -ltoolsa -lm
LOC_LIBS =

HDRS =

SRCS = degminsec2deg.c

#
# standard targets
#

include $(RAP_MAKE_INC_DIR)/rap_make_targets

#
# local targets
#

# DO NOT DELETE THIS LINE -- make depend depends on it.
