###########################################################################
#
# Makefile for test program
#
# Mike Dixon, RAP, NCAR, Boulder, CO, 80307, USA
#
# Nov 1994
#
###########################################################################

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGET_FILE = term

LOC_INCLUDES =
LOC_CFLAGS =
LOC_LDFLAGS =
LIBS = -ltitan -ltoolsa -lm

MODULE_TYPE=program

HDRS =

SRCS = term.c

#
# standard targets
#

include $(RAP_MAKE_INC_DIR)/rap_make_targets

#
# local targets
#

depend: depend_generic

# DO NOT DELETE THIS LINE -- make depend depends on it.
