###########################################################################
#
# Makefile for swap_si32 program
#
# Mike Dixon, RAP, NCAR, Boulder, CO, 80307, USA
#
# July 1996
#
###########################################################################

include $(RAP_MAKE_INC_DIR)/rap_make_macros

MODULE_TYPE = program
TARGET_FILE = swap_si32

LOC_INCLUDES =
LOC_CFLAGS =
LOC_LDFLAGS =
LOC_LIBS = \
	-lrapmath -ltoolsa -ldataport -lbz2 \
	-lm

HDRS =

SRCS = swap_si32.c

#
# standard targets
#

include $(RAP_MAKE_INC_DIR)/rap_make_targets

#
# local targets
#

# DO NOT DELETE THIS LINE -- make depend depends on it.

