#! /bin/env perl

#
# script to generate event list from storm files
#

sub print_usage {

  printf(STDERR "%s",
	 "Usage : $prog event_list <file_list>\n");
  printf(STDERR "  event_list - list of storm events\n");
  printf(STDERR "  file_list - list of storm header files\n");

}

#
# check usage
#

($prog = $0) =~ s%.*/%%;
 
if (@ARGV < 2) {
  &print_usage();
  exit(-1);
}

$event_list = shift(@ARGV);


#
# set flushing on
#

$| = 1;

#
# open events list file
#

if (open(EVENT_LIST, ">$event_list") == 0) {
  printf ("Cannot open $event_list\n");
  &print_usage();
  exit(-1);
}

printf (EVENT_LIST "#\n");
printf (EVENT_LIST "# Event list file generated by $prog\n");
printf (EVENT_LIST "# %s", `date`);
printf (EVENT_LIST "#\n");

#
# get event data from file list
#

foreach $filename (@ARGV) {
  
#
# get the view_file output
#
  
  open(VIEW_FILE_OUTPUT, "view_file -summary $filename 2>/dev/null |");
  
  $start_found = 0;
  $end_found = 0;
  
  while ($line = <VIEW_FILE_OUTPUT>) {
    
    if ($line =~ m%^\s*Start\s+:\s+\d+/\d+/\d+\s+\d+:\d+:\d+\s*%) {
      
      ($start_year, $start_month, $start_day,
       $start_hour, $start_min, $start_sec) =
	 ($line =~
	  m%^\s*Start\s+:\s+(\d+)/(\d+)/(\d+)\s+(\d+):(\d+):(\d+)\s*%);
      
      $start_found = 1;
    }
    
    if ($line =~ m%^\s*End\s+:\s+\d+/\d+/\d+\s+\d+:\d+:\d+\s*%) {
      
      ($end_year, $end_month, $end_day,
       $end_hour, $end_min, $end_sec) =
	 ($line =~
	  m%^\s*End\s+:\s+(\d+)/(\d+)/(\d+)\s+(\d+):(\d+):(\d+)\s*%);
      
      $end_found = 1;
    }
    
  }

  close (VIEW_FILE_OUTPUT);

  if ($start_found && $end_found) {
    
    printf(STDOUT "start %s %s %s %s %s %s ",
	   $start_year, $start_month, $start_day,
	   $start_hour, $start_min, $start_sec);
    printf(STDOUT "end %s %s %s %s %s %s\n",
	   $end_year, $end_month, $end_day,
	   $end_hour, $end_min, $end_sec);
    
    printf(EVENT_LIST "start %s %s %s %s %s %s ",
	   $start_year, $start_month, $start_day,
	   $start_hour, $start_min, $start_sec);
    printf(EVENT_LIST "end %s %s %s %s %s %s\n",
	   $end_year, $end_month, $end_day,
	   $end_hour, $end_min, $end_sec);
    
  }

}

close (EVENT_LIST);

exit (0);


