#! /usr/local/bin/perl

#
# Expands high terrain value to triangle icon in ZEB map format
#

$delta2 = 0.002;
$delta1 = 0.001;
$ncoords = 16;

while ($line = <>) {

  ($ref_lat, $ref_lon) = ($line =~ m%\s*(\S+)\s+(\S+).*%);

  printf(STDOUT "  %d  %.4f  %.4f  %.4f  %.4f ! peak icon\n",
	 $ncoords,
	 $ref_lat - 0.5 * $delta2,
	 $ref_lat + 1.0 * $delta2,
	 $ref_lon - 0.866 * $delta2,
	 $ref_lon + 0.866 * $delta2);
	 
  printf(STDOUT "    %.4f  %.4f  ",
	 $ref_lat + 1.0 * $delta2,
	 $ref_lon + 0.0 * $delta2);

  printf(STDOUT "%.4f  %.4f  ",
	 $ref_lat - 0.5 * $delta2,
	 $ref_lon - 0.866 * $delta2);

  printf(STDOUT "%.4f  %.4f  ",
	 $ref_lat - 0.5 * $delta2,
	 $ref_lon + 0.866 * $delta2);

  printf(STDOUT "%.4f  %.4f  ",
	 $ref_lat + 1.0 * $delta2,
	 $ref_lon + 0.0 * $delta2);

  printf(STDOUT "\n");

  printf(STDOUT "    %.4f  %.4f  ",
	 $ref_lat + 1.0 * $delta1,
	 $ref_lon + 0.0 * $delta1);

  printf(STDOUT "%.4f  %.4f  ",
	 $ref_lat - 0.5 * $delta1,
	 $ref_lon - 0.866 * $delta1);

  printf(STDOUT "%.4f  %.4f  ",
	 $ref_lat - 0.5 * $delta1,
	 $ref_lon + 0.866 * $delta1);

  printf(STDOUT "%.4f  %.4f  ",
	 $ref_lat + 1.0 * $delta1,
	 $ref_lon + 0.0 * $delta1);

  printf(STDOUT "\n");

}

