#! /bin/csh

grep LdataInfo */*.cc
grep LdataInfo */*/*.cc
grep LdataInfo */*/*/*.cc
grep LdataInfo */*/*/*/*.cc
grep LdataInfo */*/*/*/*/*.cc
grep LdataInfo */*/*/*/*/*/*.cc
grep LdataInfo */*/*/*/*/*/*/*.cc
grep LdataInfo */*/*/*/*/*/*/*/*.cc
