#!/bin/sh
# snuff - kill processes by name, for BSD or SysV.
# Version 3.0  2/2/93
# Tres Hofmeister <tres@ncar.ucar.edu>
# usage: $0 process[es]

PATH=/bin:/usr/bin:/usr/ucb

# List of signals to try.
signals="INT QUIT TERM KILL"

prog=`basename $0`

if [ $# -eq 0 ]; then
	echo "Usage: $prog process[es]" >&2
	exit 1
fi

# Is this BSD or SysV?
if [ -f /vmunix ]; then
	BSD="true"
fi

# Loop over each pattern on the command line.
for proc in "$@"
do
	# Quote any '/' characters in the pattern.
	pat=`echo "$proc" | sed 's%/%\\\/%g'`

	# A process name is considered to start with either a space
	# or '/', and end with either a space or an end of line.
	if [ "$BSD" ]; then
		pids=`ps xww | awk '/( |\/)'"$pat"'( |$)/ && \
			$0 !~ / awk |'$prog'/ {print $1}'`
	else
		pids=`ps -ef  | awk '/( |\/)'"$pat"'( |$)/ && \
			$0 !~ / awk |'$prog'/ {print $2}'`
	fi

	# Do any processes match this pattern?
	if [ "$pids" ]; then
		inst=`echo $pids | wc -w`
		echo "Instances of $proc:" $inst

		# Loop over each instance of this pattern.
		for pid in $pids
		do
			echo " Killing $proc, PID $pid"

			# Is this process killable by this UID?
			error=`kill -0 $pid 2>&1`
			if [ "$error" ]; then
				echo " $prog: $error" >&2
				# Next PID.
				continue
			fi

			# Try each signal in the list.
			for sig in $signals
			do
				kill -$sig $pid; sleep 1
				if kill -0 $pid > /dev/null 2>&1; then
					echo "  SIG$sig failed" >&2
			else
				echo "  SIG$sig succeeded"
				# Next PID.
				continue 2
				fi
			done

			if kill -0 $pid > /dev/null 2>&1; then
				echo "Failed to kill $proc, pid $pid" >&2
			fi
		done
	else
		# No processes match this pattern.
		echo "$proc: no such process" >&2
	fi
done

exit 0
