#! /bin/env perl

#
# script to generate storm_ident and storm_track scripts from an
# event list
#

sub print_usage {

  printf(STDERR "%s%s",
	 "Usage : $prog event_list ident_script ident_params ",
	 "track_script track_params\n");
  printf(STDERR "  event_list - list of storm events\n");
  printf(STDERR "  ident_script - storm_ident script name\n");
  printf(STDERR "  ident_params - storm_ident params file\n");
  printf(STDERR "  track_script - storm_track script name\n");
  printf(STDERR "  track_params - storm_track params file\n");

}

#
# check usage
#

($prog = $0) =~ s%.*/%%;
 
if (@ARGV != 5) {
  &print_usage();
  exit(-1);
}

$event_list = shift(@ARGV);
$ident_script = shift(@ARGV);
$ident_params = shift(@ARGV);
$track_script = shift(@ARGV);
$track_params = shift(@ARGV);

#
# read in events
#

if (open (EVENTS, $event_list) == 0) {
  printf ("Cannot open $event_list\n");
  &print_usage();
  exit(-1);
}

$n_events = 0;

while ($line = <EVENTS>) {
  
#
# only process lines which conform to the params spec
#
# "start yyyy mm dd hh mm ss end yyyy mm dd hh mm ss"
#

  if (!($line =~ /^start\s+\d+\s+\d+\s+\d+\s+\d+\s+\d+\s+\d+\s+end\s+\d+\s+\d+\s+\d+\s+\d+\s+\d+\s+\d+/)) {
    next;
  }

#
# read in start and end times
#

  ($start_year[$n_events], $start_month[$n_events], $start_day[$n_events],
   $start_hour[$n_events], $start_min[$n_events], $start_sec[$n_events],
   $end_year[$n_events], $end_month[$n_events], $end_day[$n_events],
   $end_hour[$n_events], $end_min[$n_events], $end_sec[$n_events]) =
     ($line =~ m%^\s*\S*\s*(\S*)\s*(\S*)\s*(\S*)\s*(\S*)\s*(\S*)\s*(\S*)\s*\S*\s*(\S*)\s*(\S*)\s*(\S*)\s*(\S*)\s*(\S*)\s*(\S*)%);

  $n_events++;

} # while

close(EVENTS);

printf(STDOUT "\nEvent list in file %s\n\n", $event_list);

for ($i = 0; $i < $n_events; $i++) {
  printf(STDOUT "Event %d ", $i);
  printf(STDOUT "start %s %s %s %s %s %s ",
	 $start_year[$i], $start_month[$i], $start_day[$i],
	 $start_hour[$i], $start_min[$i], $start_sec[$i]);
  printf(STDOUT "end %s %s %s %s %s %s\n",
	 $end_year[$i], $end_month[$i], $end_day[$i],
	 $end_hour[$i], $end_min[$i], $start_sec[$i]);
}

#
# generate storm_ident script
#

if (open (IDENT_SCRIPT, ">$ident_script") == 0) {
  printf ("Cannot open $ident_script for writing\n");
  exit(-1);
}

printf(IDENT_SCRIPT "#! /bin/csh\n");
printf(IDENT_SCRIPT "#\n");
printf(IDENT_SCRIPT "# storm_ident script - generated by $prog\n");
printf(IDENT_SCRIPT "# %s", `date`);
printf(IDENT_SCRIPT "#\n");

for ($i = 0; $i < $n_events; $i++) {

  printf(IDENT_SCRIPT "storm_ident -mode archive ");
  printf(IDENT_SCRIPT "-params %s ", $ident_params);
  printf(IDENT_SCRIPT "-starttime %s/%s/%s_%s:%s:%s ",
	 $start_year[$i], $start_month[$i], $start_day[$i],
	 $start_hour[$i], $start_min[$i], $start_sec[$i]);
  printf(IDENT_SCRIPT "-endtime %s/%s/%s_%s:%s:%s ",
	 $end_year[$i], $end_month[$i], $end_day[$i],
	 $end_hour[$i], $end_min[$i], $end_sec[$i]);
  printf(IDENT_SCRIPT "\n");

}

#
# generate storm_track script
#

if (open (TRACK_SCRIPT, ">$track_script") == 0) {
  printf ("Cannot open $track_script for writing\n");
  exit(-1);
}

printf(TRACK_SCRIPT "#! /bin/csh\n");
printf(TRACK_SCRIPT "#\n");
printf(TRACK_SCRIPT "# storm_track script - generated by $prog\n");
printf(TRACK_SCRIPT "# %s", `date`);
printf(TRACK_SCRIPT "#\n");

for ($i = 0; $i < $n_events; $i++) {

  printf(TRACK_SCRIPT "storm_track -mode retrack ");
  printf(TRACK_SCRIPT "-params %s ", $track_params);
  printf(TRACK_SCRIPT "-f %s%s%s.sh3",
	 $start_year[$i], $start_month[$i], $start_day[$i]);
  printf(TRACK_SCRIPT "\n");

}

#
# force flushing for stdout
#

$| = 1;
printf(STDOUT "\0");

exit (0);

