#! /usr/local/bin/perl

#
# Convert zeb map format to MIF format
#

#
# proglog
#

printf (STDOUT "<MIFFile 3.00> # generated by zeb2mif\n");
printf (STDOUT "<Units Ucm>\n");

#
# bounding coords for source (map coords)
#

$source_minx = 113.8235;
$source_miny = 22.1931;
$source_maxx = 114.5099;
$source_maxy = 22.6076;

$source_dx = $source_maxx - $source_minx;
$source_dy = $source_maxy - $source_miny;

#
# bounding coords for target (page)
#

$target_minx = 0.0;
$target_miny = 0.0;
$target_maxx = 20.0;
$target_maxy = 14.55;

$target_dx = $target_maxx - $target_minx;
$target_dy = $target_maxy - $target_miny;

$scale_x = $target_dx / $source_dx;
$scale_y = $target_dy / $source_dy;

#print $scale_x, "\n";
#print $scale_y, "\n";

while ($line = <>) {

#
# strip off any comments and leading whitespace, and
# split into tokens
#

#  print $line;

  $line =~ s/\s*!.*$//;
  $line =~ s/^\s*//;
  @tokens = split(/\s+/, $line);
  $ntokens = $#tokens + 1;

  if ($ntokens != 5) {
    printf (STDOUT "BAD HEADER LINE, line %d\n", $.);
    exit();
  }

  $ncoords = $tokens[0];

  $npoints = int($ncoords / 2);

  $coords_so_far = 0;

#  printf (STDOUT "ncoords = %d\n", $ncoords);

  @coords = ();

#
# loop through lines with coords
#

  while ($coords_so_far < $ncoords) {

    $line = <>;
    $line =~ s/\s*!.*$//;
    $line =~ s/^\s*//;
    @tokens = split(/\s+/, $line);
    $ntokens = $#tokens + 1;

#    print $line;
#    printf (STDOUT "coords_so_far, ntokens = %d, %d\n",
#	    $coords_so_far, $ntokens);

    $coords_so_far += $ntokens;

    push(@coords, @tokens);

  }

  printf (STDOUT "  <PolyLine\n");
  printf (STDOUT "    <GroupID 1>\n");
  printf (STDOUT "    <Fill 15>\n");
  printf (STDOUT "    <NumPoints %d>\n", $npoints);
  
  for ($i = 0; $i < $npoints; $i++) {

    $lat = $coords[$i * 2];
    $lon = $coords[($i * 2) + 1];

    $xx = ($lon - $source_minx) * $scale_x + $target_minx;
    $yy = $target_maxy - (($lat - $source_miny) * $scale_y + $target_miny);

#    printf (STDOUT "%d\n", $i);
#    printf (STDOUT "%f, %f\n", $lon, $lat);
 
    printf (STDOUT "    <Point %f %f>\n", $xx, $yy);

  }
    
  printf (STDOUT "  >\n");

}


