###########################################################################
#
# Makefile for ttest program
#
# Mike Dixon, RAP, NCAR, Boulder, CO, 80307, USA
#
# July 1996
#
###########################################################################

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGET_FILE = ttest

LOC_INCLUDES =
LOC_CFLAGS =
LOC_LDFLAGS =
LOC_LIBS = \
	-ltoolsa -ldataport -lbz2

HDRS =

SRCS = ttest.c

#
# standard targets
#

include $(RAP_MAKE_INC_DIR)/rap_make_c_targets

#
# local targets
#

# DO NOT DELETE THIS LINE -- make depend depends on it.

