
include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGET_FILE = TcpIpTest

LOC_INCLUDES = -I.
LOC_CFLAGS =
LOC_LDFLAGS =
LOC_LIBS = \
	-ltoolsa -lbz2

MODULE_TYPE = progcpp

HDRS = 

C_SRCS =

CPPC_SRCS = \
	TcpIpTest.cc

#
# standard targets
#

include $(RAP_MAKE_INC_DIR)/rap_make_c++_targets

#
# local targets
#

depend: depend_generic

# DO NOT DELETE THIS LINE -- make depend depends on it.




